# Automatically generated by Sovereign Quant Engine
# Strategy Name: SovereignStrategy
import jesse.indicators as ta
from jesse.strategies import Strategy

from .params import params


class SovereignStrategy(Strategy):
    @property
    def current_regime(self) -> str:
        return "trending_bullish"

    @property
    def hyperparameters(self):
        if isinstance(params, dict) and "default" in params:
            return params.get(self.current_regime, params.get("default", params))
        return params

    @property
    def rsi(self) -> float:
        return ta.rsi(self.candles, period=14)

    @property
    def sma(self) -> float:
        return ta.sma(self.candles, period=50)

    def should_long(self) -> bool:
        # Long entry conditions:
        # rsi < 30
        # close > sma
        return self.rsi < 30 and self.price > self.sma

    def should_short(self) -> bool:
        # Short entry conditions:
        # rsi > 70
        # close < sma
        return self.rsi > 70 and self.price < self.sma

    def should_cancel_entry(self) -> bool:
        return False

    @property
    def atr(self) -> float:
        # ATR indicator calculation using Jesse ta module
        return ta.atr(self.candles)

    def go_long(self):
        # Volatility-based sizing (ATR-based sizing):
        # Risk amount = Capital * max_position_sizing_pct / 100
        # Stop distance = ATR * 2
        # Qty = Risk amount / Stop distance
        try:
            stop_distance = self.atr * 2
            risk_pct = self.hyperparameters["risk"]["max_position_sizing_pct"] / 100.0
            risk_amount = self.capital * risk_pct
            qty = risk_amount / stop_distance
        except Exception:
            # Fallback to default sizing if indicators/candles aren't fully loaded
            qty = self.capital / self.price

        self.buy = qty, self.price
        sl_value = self.hyperparameters["risk"]["stop_loss_value"]
        tp_value = self.hyperparameters["risk"].get("take_profit_value", sl_value * 2)
        self.stop_loss = qty, self.price * (1 - sl_value)
        self.take_profit = qty, self.price * (1 + tp_value)

    def go_short(self):
        # Volatility-based sizing (ATR-based sizing):
        try:
            stop_distance = self.atr * 2
            risk_pct = self.hyperparameters["risk"]["max_position_sizing_pct"] / 100.0
            risk_amount = self.capital * risk_pct
            qty = risk_amount / stop_distance
        except Exception:
            qty = self.capital / self.price

        self.sell = qty, self.price
        sl_value = self.hyperparameters["risk"]["stop_loss_value"]
        tp_value = self.hyperparameters["risk"].get("take_profit_value", sl_value * 2)
        self.stop_loss = qty, self.price * (1 + sl_value)
        self.take_profit = qty, self.price * (1 - tp_value)

    def _update_trailing_stop(self):
        sl_value = self.hyperparameters["risk"]["stop_loss_value"]
        if self.is_long:
            new_sl = self.price * (1 - sl_value)
            if new_sl > self.average_entry_price * (1 - sl_value):
                self.stop_loss = self.position.qty, new_sl
        elif self.is_short:
            new_sl = self.price * (1 + sl_value)
            if new_sl < self.average_entry_price * (1 + sl_value):
                self.stop_loss = self.position.qty, new_sl

    def _update_atr_stop(self):
        atr_val = self.atr
        if self.is_long:
            self.stop_loss = self.position.qty, self.price - atr_val * 2
        elif self.is_short:
            self.stop_loss = self.position.qty, self.price + atr_val * 2

    def update_position(self):
        # Dynamic stop-loss management based on stop_loss_type
        sl_type = self.hyperparameters["risk"].get("stop_loss_type", "fixed")
        if sl_type == "trailing":
            self._update_trailing_stop()
        elif sl_type == "atr":
            self._update_atr_stop()
