# Automatically generated by Sovereign Quant Engine
# Strategy Name: SovereignStrategy
from jesse.strategies import Strategy
import jesse.indicators as ta
from .params import params

class SovereignStrategy(Strategy):
    @property
    def current_regime(self) -> str:
        return 'trending_bullish'

    @property
    def hyperparameters(self):
        if isinstance(params, dict) and 'default' in params:
            return params.get(self.current_regime, params.get('default', params))
        return params
    @property
    def rsi(self) -> float:
        return ta.rsi(self.candles, period=14)

    @property
    def sma(self) -> float:
        return ta.sma(self.candles, period=50)

    def should_long(self) -> bool:
        # Long entry conditions:
        # rsi < 30
        # close > sma
        return self.rsi < 30 and self.price > self.sma

    def should_short(self) -> bool:
        # Short entry conditions:
        # rsi > 70
        # close < sma
        return self.rsi > 70 and self.price < self.sma

    def should_cancel_entry(self) -> bool:
        return True

    def go_long(self):
        qty = 1.0
        self.buy = qty, self.price

    def go_short(self):
        qty = 1.0
        self.sell = qty, self.price

    def update_position(self):
        pass
