# Automatically generated by Sovereign Quant Engine
params = {   'default': {   'indicators': {'rsi': {'period': 14}, 'sma': {'period': 50}},
                   'risk': {   'max_drawdown_limit_pct': 1.5,
                               'max_position_sizing_pct': 2.0,
                               'stop_loss_type': 'fixed',
                               'stop_loss_value': 0.02}},
    'trending_bullish': {   'indicators': {   'rsi': {'period': 14},
                                              'sma': {'period': 50}},
                            'risk': {   'max_drawdown_limit_pct': 1.5,
                                        'max_position_sizing_pct': 2.0,
                                        'stop_loss_type': 'fixed',
                                        'stop_loss_value': 0.02}}}
